NUbots/NUbook

gatsby-config.js, package.json, src/styles/global.css, tailwind.config.js, yarn.lock
Adds [purgecss](https://www.purgecss.com/) to remove unused styles when building for production. Especially important for Tailwind. Reduces CSS size by more than 90%.
<pre><span style="color: #4E9A06">gatsby-plugin-purgecss:</span>
<span style="color: #06989A"> Previous CSS Size: 633.84 KB</span>
<span style="color: #06989A"> New CSS Size: 48.67 KB (-92.32%)</span>
<span style="color: #C4A000"> Removed ~585.17 KB of CSS</span>
</pre>
=> Optimize build for production

src/components/article-header.jsx
This fixes the article header from #6 for pages without a chapter or section (like the kitchen sink).
=> Fix article header for pages without a chapter or section

.gitattributes
Forces Windows to format to LF rather than CRLF
=> Ensures LF endings rather than CRLF

README.md, package.json, src/book/02-projects/03-hardware/01-overview.mdx, src/book/kitchen-sink.mdx
This PR adds support for Netlify deploys:
- Deploys pull requests and commits, and updating checks on GitHub
- Deploys merge commits on master to the main site
- Removes missing images that are blocking a deploy. They're added again in #13. 
- Updates README with new deploy information
Preview link for this PR: https://deploy-preview-14--nubook.netlify.com/
=> Add auto deploys

src/book/kitchen-sink.mdx, src/components/markdown/alert/alert.jsx, src/components/markdown/alert/alert.module.css, src/components/markdown/code.jsx, src/components/markdown/heading/heading.jsx, src/components/markdown/markdown.module.css
This refactors the CSS applied to markdown content and fixes a number of issues with things like:
- [Code](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#headers-with-code) and [links](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#headers-with-links) nested in headings
- Paragraphs, links, code, math, etc nested in [alerts](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#alerts)
- Paragraphs, links, code, math, etc nested in [blockquotes](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#blockquotes)
- Paragraphs, links, code, math, etc nested in [`<details>`](https://deploy-preview-26--nubook.netlify.com/kitchen-sink#collapsible-content)
- Arbitrarily nested [ordered and unordered lists](https://deploy-preview-26--nubook.netlify.com/kitchen-sin …
=> Improve Markdown content styles

src/components/sidebar/sidebar.jsx
This PR fixes the issue where the scroll to the active link in the sidebar also scrolls the main content area.
To see current behaviour, go to https://nubook.netlify.com/team/publications and scroll about halfway down the page, then click **Team History** in the sidebar. You'll notice that (in Chrome) the main content has been scrolled, and doesn't show the page title.
To see the fix, do the same here: https://deploy-preview-39--nubook.netlify.com/team/publications
=> Fix content scroll issue when switching from long pages

README.md, src/book/kitchen-sink.mdx, src/components/markdown/markdown.jsx, src/components/markdown/tabbed-images.jsx
This PR adds a `TabbedImages` component that can be used to show images side-by-side in tabs.
Extracted from #25 where it is used to show two alternate diagrams.
Looks like this:
[Preview](https://deploy-preview-42--nubook.netlify.com/kitchen-sink#tabbed-images)
=> Add component to show images in tabs

package.json
This fixes the following errors:
Currently Prettier's `mdx` parser [is broken](https://github.com/prettier/prettier/issues/7041), and fails when trying to parse JSX code blocks.
This is why code like this result in an error:
````mdx
<Alert>
```js
alert('oh hai')
```
</Alert>
````
Strangely, there's no error when using the `markdown` parser. So this PR adds a parser override to force Prettier to use the `markdown` parser for `.mdx` files.
=> Fix Prettier format error

src/components/layout.jsx, src/components/sidebar/sidebar.jsx
This PR fixes anchor links (links that scroll to a specific section on the page).
It was broken due to the way we focused the active link in the sidebar.
Compare [this link](https://nubook.nubots.net/system/foundations/mathematics#velocity) (master, broken) with [the same link here](https://deploy-preview-76--nubook.netlify.app/system/foundations/mathematics#velocity) (this PR, fixed). Both links should open the Mathematics page and scroll to the Velocity section, but only the second works.
=> Fix anchor links

src/book/02-system/01-foundations/02-build-system.mdx
Adds documentation for new `./b tests`.
[Preview](https://deploy-preview-98--nubook.netlify.com/system/foundations/build-system#tests)
=> bscript tests tool documentation

src/book/03-guides/02-tools/03-webots.mdx
This changes the Webots guide to install the Robocup TC's fork of Webots, and adds instructions to change the webots download mirrors to use [our version on GitHub](https://github.com/NUbots/WebotsDependenciesMirror).
With this change installs are a lot faster (downloads take minutes instead of hours). 
[Preview](https://deploy-preview-108--nubook.netlify.app/guides/tools/webots-setup#install-webots)
=> Update webots guide to use Robocup TC fork, add instructions to change mirrors

src/book/02-system/01-foundations/04-nuclear.mdx, src/book/02-system/02-subsystems/01-input.mdx, src/book/02-system/02-subsystems/04-motion.mdx, src/book/02-system/02-subsystems/05-vision.mdx, src/book/02-system/02-subsystems/06-behaviour.mdx, src/book/02-system/02-subsystems/07-logging.mdx, src/book/02-system/03-tools/03-nupbr.mdx, src/book/02-system/03-tools/04-nugan.mdx, src/book/kitchen-sink/02-formatting-paragraphs.mdx, src/book/kitchen-sink/03-blockquotes.mdx, src/book/kitchen-sink/05-images.mdx, src/book/kitchen-sink/06-lists.mdx, src/book/kitchen-sink/07-code.mdx, src/book/kitchen-sink/08-math.mdx, src/book/kitchen-sink/10-tables.mdx, src/book/kitchen-sink/11-collapsible-content.mdx
Some pages started with level 1 headings (`#`), however this is technically incorrect. A level 1 heading is automatically generated on the page for the title of the page. Contributers to NUbook should start with level 2 headings (`##`) in markdown files. 
The NUpbr page had heading level 3 skipped, this was fixed so that the headers progressed correctly.
=> Fixes heading levels so that they progress correctly

src/book/02-system/01-foundations/03-continuous-integration.mdx, src/book/02-system/02-subsystems/07-logging.mdx, src/book/02-system/03-tools/02-nubook.mdx, src/book/02-system/03-tools/04-nugan.mdx, src/book/03-guides/02-tools/03-webots.mdx, src/book/03-guides/03-hardware/02-flashing.mdx, src/book/03-guides/04-general/01-git.mdx, src/book/03-guides/04-general/02-troubleshooting.mdx
This will correctly highlight comments, command names, and other shell syntax.
=> Replace `sh` with `bash` in terminal code blocks for proper syntax highlighting

src/book/03-guides/01-main-codebase/01-getting-started.mdx, src/book/03-guides/02-tools/02-gazebo-install.mdx, src/book/03-guides/02-tools/04-visualmesh.mdx
Some of our guides didn't have the "bash" tag for code blocks which affects syntax highlighting
[Preview](https://deploy-preview-154--nubook.netlify.app/guides/main/getting-started)
=> Fix bash consistency

src/book/03-guides/01-main-codebase/01-getting-started.mdx
- Fixes a stray incorrect link to the NUsight section after the NUsight section's heading was changed
- Fixes the command that gets the container's IP address on Windows and macOS
=> Updates the Getting Started Page [Sep 2021] 

src/book/03-guides/02-tools/03-webots.mdx
Added a potential fix if Webots crashes with an error on Windows OS
=> Updated "Setting Up Webots" page in section: Prerequisites - Windows

src/components/contributions/contributions.jsx, src/components/layout.jsx, src/components/page-template.jsx
Addresses #192 
- Adds list of page contributors to the contributions/last updated section.
The name tool-tips currently use the `title` attribute as I had trouble implementing the tool-tips shown in the [mock-up](https://github.com/NUbots/NUbook/issues/192#issue-1022549762).
[Preview](https://deploy-preview-204--nubook.netlify.app/system/foundations/build-system)
=> Add contributor list to contributions section

src/components/layout.jsx
Ensures that the contributor component only renders when a commit is returned by the GitHub API. 
This prevents the contributor component from accessing undefined properties on new or renamed pages that don't exist on the main branch (see [discussion](https://github.com/NUbots/NUbook/pull/183#issuecomment-1013558037)).
=> Fix contributors component accessing undefined properties on new pages

src/book/02-system/03-tools/02-nubook.mdx, src/book/kitchen-sink/05-images.mdx, src/components/markdown/grid/grid.jsx, src/components/markdown/grid/grid.module.css
Allows for customising the spacing between items in the grid. Useful for things like [maths equations](https://github.com/NUbots/NUbook/pull/201).
Preview: https://deploy-preview-203--nubook.netlify.app/kitchen-sink/images#different-grid-gaps
Documentation: https://deploy-preview-203--nubook.netlify.app/system/tools/nubook#content-in-grids
=> Add `gap` property to `Grid` component

build-plugins/remark-absolute-image-src.js, package.json, static/algolia-search.js
Currently files in `build-plugins/` and `static/` are not checked for formatting with `yarn format:check`. This PR remedies that, and fixes a formatting issue in two of the files.
=> Ensure files in `build-plugins/` and `static/` are formatted

src/book/03-guides/01-main-codebase/01-getting-started.mdx
Windows NUsight instructions don't  work. This PR
1. Removes the Windows-specific method and makes the Linux method the generic method for NUsight, but with separate methods for getting the address of the container
2. Removes the node and yarn installations since it's all in docker
3. Removes the comment about setting up nuclearnet when running for Windows and macOS in the section on running the code
4. Removes the comment about turning on the right messages since they're all on by default
https://deploy-preview-283--nubook.netlify.app/guides/main/getting-started
=> Update NUsight instructions on the Getting Started page

CODE_OF_CONDUCT.md, src/components/footer/footer.jsx
The University has a fresh Code of Conduct PDF up online. The old link no longer works so this PR updates to the new one.
<https://deploy-preview-287--nubook.netlify.com/>
Code of Conduct is in footer
=> Fix the Code of Conduct Links

src/book/02-system/03-tools/06-natnet.mdx, src/book/03-guides/01-main-codebase/05-recording-playback.mdx, src/book/03-guides/01-main-codebase/06-camera-calibration.mdx
This PR updates references to `log/` as the DataLogging output directory to `recordings/`, to match https://github.com/NUbots/NUbots/pull/1282.
Changed pages:
- https://deploy-preview-301--nubook.netlify.app/system/tools/natnet_sdk
- https://deploy-preview-301--nubook.netlify.app/guides/main/data-recording-playback
- https://deploy-preview-301--nubook.netlify.app/guides/main/camera-calibration
=> Update references to DataLogging default output path

src/book/01-team/04-history/03-publications.mdx
Adds in some publications from this year.
Adds in previous theses (phd and masters) from previous years, since they probably fit on this page. 
<https://deploy-preview-300--nubook.netlify.com/team/publications>
=> Add Publications from 2023 and Theses

src/book/03-guides/02-tools/02-webots.mdx
We should be using our fork of NUbots/hlvs_webots, as it has up to date robot models, and a tailored json for us.
<https://deploy-preview-302--nubook.netlify.com/guides/tools/webots-setup>
=> Change from TC repo to our repo for hlvs_webots

.github/pull_request_template.md
PR template is what shows up in the description text box when you make a PR.
Currently the link in the template is wrong, so this updates it (.app instead of .com).
=> Fix the preview link in the PR template

src/book/02-system/01-foundations/07-director.mdx
For NUbots/NUbots#1519 and for the previous NUClear and Director API changes 
- Adds Wait Task info
- Changes Idle to Continue
- Changes `NUClear::INFO` to `INFO`
<https://deploy-preview-321--nubook.netlify.app/system/foundations/director>
=> Add Director Wait and update API changes

src/book/01-team/01-introduction/01-introduction-to-nubots.mdx, src/book/01-team/01-introduction/03-current-team.mdx, src/book/01-team/02-joining/01-how-we-work.mdx, src/book/01-team/02-joining/02-how-to-join.mdx, src/book/01-team/03-community/01-sponsors.mdx
More minor things with location change, removed meeting time because this page isn't updated frequently enough for it to be useful, updated the intro page (very old, still had me as team leader), removed sponsorship that's ended now. Biggest change is the current members section. Seems to be a year or more old. I think we're trying to chase up some people so I'll give this some time to settle. @Claegtun you might want to have a look.
https://deploy-preview-328--nubook.netlify.app/team/current-members
=> Update team section, including current members
