gatsby-config.js
package.json
scripts/verify-deploy-branch.js
yarn.lock

This adds a script that builds the site and deploys to Github Pages.
To deploy, run:
```bash
yarn deploy
```
TODO:

Add deploy script

---

README.md
src/book/01-team/01-introduction/01-introduction-to-nubots.mdx
src/book/02-projects/01-nubots/01-overview.mdx
src/book/02-projects/03-hardware/01-overview.mdx
src/book/kitchen-sink.mdx

This PR updates image references to match changes in #6.

Update image references

---

README.md
src/book/kitchen-sink.mdx
src/components/markdown/code.jsx
src/components/markdown/grid/grid.jsx
src/components/markdown/grid/grid.module.css
src/components/markdown/image.jsx
src/components/markdown/markdown.jsx
src/components/markdown/markdown.module.css

This PR adds support for displaying images and other content side-by-side in a grid.
[Preview in the Kitchen Sink](https://5d947b0b7073e9000d63aa79--nubook.netlify.com/kitchen-sink#grid).
```mdx
<Grid columns='1fr 1fr' rows="1fr 1fr" caption="Some possible pets">
</Grid>
```
<details>
<summary>Source</summary>
````mdx
<Grid columns='1fr 1fr' caption="Hello world in different languages" seamless>
```java
// Java
public class HelloWorld {
public static void main(String[] args) {
System.out.println("Hello world!");
}
}
```
```cpp
// C++
int main(void) {
std::cout << "Hello world!" << std::endl;
return 0;
}
```
```py
print('Hello world!')
```
```js
// JavaScript
console.log('Hello world!')
```
```php
// PHP
<?php
echo 'Hello world!';
?>
```
```c
// C
int main(void) {
printf("Hello world!"); …

Add support for displaying images and other content in grids

---

src/book/02-system/03-hardware/01-overview.mdx

[Preview](https://deploy-preview-43--nubook.netlify.com/system/hardware/overview#foot-studs)

Add information on the foot studs

---

src/book/02-system/01-nubots/02-build-system.mdx

Pairs with [this PR](https://github.com/NUbots/NUbots/pull/294) in the NUbots codebase
[Preview](https://deploy-preview-47--nubook.netlify.com/system/nubots/build-system#run)

Add information about the debugging options in the run command

---

README.md
src/book/01-team/02-joining/01-how-we-work.mdx

Some things that were missed.
- README Node.js version
- strike through is double tilde not single

Fixes after dev day

---

src/book/02-system/01-nubots/02-build-system.mdx
src/book/03-guides/01-nubots/01-getting-started.mdx
src/book/03-guides/04-general/01-git.mdx

Linked to NUbots/NUbots#330
https://deploy-preview-63--nubook.netlify.app/guides/nubots/getting-started

Add Windows instructions to the Getting Started guide

---

src/book/02-system/01-foundations/02-build-system.mdx

For https://github.com/NUbots/NUbots/pull/329

Add information about the new filter tool

---

src/book/02-system/02-subsystems/06-logging.mdx

Pairs with [NUbots PR](https://github.com/NUbots/NUbots/pull/323)
[Preview](https://deploy-preview-65--nubook.netlify.app/system/subsystems/logging)

Add information on the DataPlayback module

---

src/book/02-system/01-foundations/02-build-system.mdx

Paired with https://github.com/NUbots/NUbots/pull/334

Rename NetworkConfiguration to NUClearNet

---

src/book/01-team/01-introduction/01-introduction-to-nubots.mdx
src/book/01-team/01-introduction/03-current-team.mdx
src/book/01-team/02-joining/01-how-we-work.mdx
src/book/01-team/04-history/01-team-history.mdx
src/book/01-team/05-robocup/02-resources.mdx
src/book/02-system/01-foundations/02-build-system.mdx
src/book/02-system/01-foundations/05-mathematics.mdx
src/book/03-guides/01-main-codebase/01-getting-started.mdx
src/book/03-guides/04-general/01-git.mdx

Anything that needs to be updated. Includes some fixes after the restructure. Some grammar fixes too. 
https://deploy-preview-66--nubook.netlify.app/

September NUbook Update

---

src/book/02-system/03-tools/01-nusight.mdx

Somehow this slipped through, probably due to incorrect rules for the master branch which is now fixed (hopefully).

Formats NUsight page

---

gatsby-config.js
gatsby-node.js
package.json
src/components/layout.jsx
yarn.lock

This PR adds some things we need in master before search can be added

Prepare for search

---

gatsby-node.js

This PR fixes the annoying issue of duplicate links in the sidebar when saving during development:

Fix duplicate links in sidebar

---

README.md

Updated the README with the new domain, and changed the netlify examples to link to what they get redirected to.

Updates README netlify links.

---

src/book/03-guides/01-main-codebase/01-getting-started.mdx

Adds more information to the Getting Started guide.
[Preview.](https://deploy-preview-78--nubook.netlify.app/guides/main/getting-started)

Updates the Getting Started Guide

---

src/book/03-guides/01-main-codebase/01-getting-started.mdx

- on/off instead of true/false for role selection in configure
- remove extra character in a command...

Fixes minor issues on the Getting Started page

---

src/components/article-header.jsx
src/components/header/search/search.jsx
src/components/header/search/search.module.css
src/components/seo.jsx
src/styles/global.css
static/algolia-search.js
stylelint.config.js

Adds real-time search!
[Preview](https://deploy-preview-82--nubook.netlify.app)

Integrate search

---

src/book/02-system/01-foundations/04-nuclear.mdx

[Preview](https://deploy-preview-92--nubook.netlify.app/system/foundations/nuclear#nbs-files)

Added documentation for nbs indexes.

---

src/book/01-team/02-joining/01-how-we-work.mdx

This PR updates the **How We Work** page with the new 2021 Semester 1 meeting time.
[Preview](https://deploy-preview-94--nubook.netlify.app/team/how-we-work)

Update meeting time for 2021 Semester 1

---

src/book/03-guides/04-general/04-visualmesh.mdx

I would suggest also adding a short troubleshooting section at the end of the document too if there'll be a number of people using this resource.

Modifications for readability and ease of setup

---

src/book/03-guides/02-tools/03-webots.mdx

Added line to description instructing to use develop branch
[preview](https://deploy-preview-103--nubook.netlify.com/guides/tools/webots-setup#install-webots)

Note to use develop branch when building

---

src/book/03-guides/02-tools/03-webots.mdx

We have new dependencies. This updates our install docs as such.

Updates Webots dependencies and adds update command when installing them

---

src/book/03-guides/02-tools/03-webots.mdx
src/book/03-guides/04-general/03-glossary.mdx

I added all of the `configure` flags from the cmake file. lmk what you think

Updates webots setup and running webots sections with `./b` stuff

---

src/book/03-guides/02-tools/03-webots.mdx
src/book/03-guides/02-tools/assets/webots_usb.patch

I am the greatest developer alive

Fixes controller generation and the arch usb patch

---

src/book/01-team/01-introduction/03-current-team.mdx

Updates the current members with the following changes
- Flattens the structure (deciding if someone is what level member is really tough and there isn't much benefit to the structure)
- Adds and updates roles and leads
- Update supporting mentors by re-adding Brendan and moving Josephus to supporting member
https://deploy-preview-136--nubook.netlify.app/team/current-members

Current Members July 2021 Update

---

src/book/01-team/02-joining/01-how-we-work.mdx

It still said Friday
[Preview](https://deploy-preview-151--nubook.netlify.app/team/how-we-work)

Update meeting time in how we work page

---

src/book/01-team/04-history/01-team-history.mdx

The caption didn't match the table. This brings it back in line
[Preview](https://deploy-preview-152--nubook.netlify.app/team/history)

Update robocup history

---

src/book/01-team/04-history/03-publications.mdx

https://deploy-preview-159--nubook.netlify.app/team/publications

Removes extra bracket `[` on some lines in the Publications page

---

src/book/02-system/01-foundations/05-mathematics.mdx

https://deploy-preview-158--nubook.netlify.app/system/foundations/mathematics#units

Changes Glossary link on Mathematics page from its mdx file to its slug

---

src/book/02-system/03-tools/02-nubook.mdx

Document `yarn build`

---

src/book/01-team/05-robocup/02-resources.mdx

Adds discord and forum links to the RoboCup resources page

---

src/book/03-guides/01-main-codebase/01-getting-started.mdx
src/book/03-guides/02-tools/03-webots.mdx

https://github.com/NUbots/NUWebots/issues/82
https://deploy-preview-182--nubook.netlify.app/guides/tools/webots-setup

Includes additional set-up instructions for windows

---

gatsby-config.js
gatsby-node.js
package.json
src/components/article-header.jsx
src/components/contributions/contributions.jsx
src/components/contributions/edit-icon.svg
src/components/layout.jsx
src/components/page-template.jsx
yarn.lock

Addresses [#186](https://github.com/NUbots/NUbook/issues/186)
Adds Last Updated section to pages as part of the Contributors component to show when the page was last updated.
[Preview](https://deploy-preview-197--nubook.netlify.app/guides/main/getting-started)

Add Contributors component

---

src/book/01-team/02-joining/01-how-we-work.mdx
src/book/01-team/02-joining/02-how-to-join.mdx
src/book/01-team/02-joining/03-induction.mdx

- Updates the meeting time in 'How We Work'
- Expands on research benefit in 'How to Join NUbots'
- Rewrite of the 'Lab Induction' page for the new Canvas system

Updates pages in the 'Joining' chapter in the 'Team' section [May 2022]

---

package.json
src/components/header/search/algolia-search.js
src/components/header/search/search.jsx
static/algolia-search-event-listener.js

[preview](https://deploy-preview-221--nubook.netlify.app/)

Fix bug where search bar stops working after clicking NUbots logo

---

src/book/03-guides/04-general/01-learning-resources.mdx

@BryceTuppurainen Posted this link to slack, I thought it would be good to be in NUbook.
https://deploy-preview-227--nubook.netlify.app/guides/general/learning-resources

Add github skills link

---

src/book/03-guides/04-general/01-learning-resources.mdx

For some reason I'm hitting this error both on main and on this branch at the moment when developing locally, but for the life of me I can't figure out where this would be or whether this is just an issue with the version of nodejs or something that I've got configured at the moment.
Anyway, if you can please check out the content and then merge this in if you can't find anything that you'd suggest fixing that'd be much appreciated.

Adds further Git learning resources and docs

---

src/book/02-system/03-tools/05-system-configuration.mdx
src/book/03-guides/03-hardware/02-flashing.mdx

Document https://github.com/NUbots/NUbots/pull/299
https://deploy-preview-245--nubook.netlify.app/system/tools/system_configuration
https://deploy-preview-245--nubook.netlify.app/guides/hardware/flashing
todo

Add documentation for System Configuration

---

src/book/01-team/01-introduction/03-current-team.mdx

Adds the new team members who joined the team last week.

Add new team members :tada:

---

src/book/03-guides/02-tools/02-webots.mdx

The folder was moved on the NUWebots repo.

Update folder in webots guide

---

src/book/02-system/01-foundations/05-mathematics.mdx
src/book/03-guides/04-general/04-code-conventions.mdx

As per [NUbots#986](https://github.com/NUbots/NUbots/pull/986)

Change from using Affine to Isometry in Eigen

---

src/book/03-guides/02-tools/04-nupbr-guide.mdx

Wasn't put in correctly. This should fix it.

Fix broken image in NUpbr guide

---

src/book/02-system/03-tools/06-natnet.mdx

Created new page for the NatNet SDK implementation present in the NUbots directory, including a brief explanation, a guide for setup of both Motive and NatNet and some explanation and tips for future developers.

Created new NatNet SDK page

---

src/book/02-system/01-foundations/02-build-system.mdx

Updates configure tool description to match changes in nubots/nubots#1031

Add brief description of configure tool changes

---

src/book/03-guides/01-main-codebase/01-getting-started.mdx

Updates the `requirements.txt` path to `tools/requirements.txt`

Updates requirements install step

---

src/book/02-system/03-tools/01-nusight.mdx
src/book/02-system/03-tools/04-nugan.mdx
src/book/02-system/03-tools/references.bib

Needed an update to use the referencing system, which this PR does.
<https://deploy-preview-295--nubook.netlify.com/system/tools/nugan>

Update the NUgan page to use the referencing system

---

src/book/01-team/05-robocup/03-debriefs.mdx

Adds the debrief we wrote up on GDrive at RoboCup to NUbook.
<https://deploy-preview-309--nubook.netlify.app/team/robocup/debriefs>

Add RoboCup 2024 Eindhoven Debrief

---

src/book/03-guides/01-main-codebase/01-getting-started.mdx

changed to Ubuntu 22.04.3
added more alerts
<https://deploy-preview-310--nubook.netlify.app/guides/main/getting-started>

Update windows instructions

---

src/book/03-guides/02-tools/02-webots.mdx

This PR moves the `Running a NUbots Environment` section to top of tutorial.
This is the most common use case for `webots` and easier for people to follow when getting started, so better to put at the top.

Shuffle webots guide order

---

src/book/03-guides/02-tools/02-webots.mdx

- Restructures
- Adds more info where gaps were, such as info on the NUWebots worlds
- Updates for NUbots/NUbots#1550
<https://deploy-preview-326--nubook.netlify.app/guides/tools/webots-setup>

Update the webots guide with new multi robot run instructions

---

src/book/01-team/04-history/03-publications.mdx

The three RoboCup papers and Alex's PhD thesis.
<https://deploy-preview-327--nubook.netlify.app/team/publications>

Add publications and completed PhD from last year

---

src/book/03-guides/02-tools/05-gamecontroller.mdx
yarn.lock

This PR adds a new page for the updated GameController, including minimal setup instructions.
https://deploy-preview-331--nubook.netlify.app/guides/tools/gamecontroller

Add New GameController page

---

src/book/03-guides/04-general/02-contribute.mdx

Changed the page into a 'contribute' page to reduce wordiness in the title. 
Addresses issue #177.
<https://deploy-preview-337--nubook.netlify.app/guides/general/contribute>

Add Jira workflow to the Git/GitHub page
